export const error = {
    USER_ALREADY_EXISTS: "User already exists",
    USER_DOES_NOT_EXIST: "User does not exist. Please register.",
    INCORRECT_PASSWORD: "Incorrect password",
    INTERNAL_SERVER_ERROR: "Internal server error",
    USER_NOT_FOUND: "User does not exist",
    NOT_FOUND: "Not found",
    USER_BLOCKED: "User is blocked",
    USER_ALREADY_VERIFIED: "User already verified",
    EMAIL_NOT_VERIFIED: "The user is not verified",
    VERIFICATION_CODE_NOT_FOUND: "Verification code does not exist",
    VERIFICATION_CODE_MISMATCH: "Verification code does not match",
    VERIFICATION_CODE_EXPIRED: "Verification code is expired",
    VERIFICATION_CODE_LIMIT_REACHED: "Daily verification code limit reached",
    VERIFICATION_CODE_EXCEEDED_ATTEMPTS_LIMIT: "Verification code entry limit reached, please try sending the code again",
    ACTIVE_SESSION_EXISTS: "A confirmation code has been sent to your email address to continue",
    INVALID_AUTHORIZATION_HEADER: "Unauthorized - Invalid Authorization header",
    INVALID_TOKEN_HEADER: "Unauthorized - Invalid token",
    REQUEST_LIMIT_EXHAUSTED: "Request limit exhausted",
    FORBIDDEN: "Access is denied",
    NOT_CITY_EXISTS: "City not found.",
    NOT_SKILL_EXISTS: "Skill does not exist",
    TOO_MANY_REQUESTS_DAILY: "Too many requests",
    RESUME_LIMIT_EXCEEDED_TOTAL: "Resume creation limit exceeded",
}