export const USER_ALREADY_EXISTS = "User already exists";
export const USER_DOES_NOT_EXIST = "User does not exist. Please register.";
export const INCORRECT_PASSWORD = "Incorrect password";
export const INTERNAL_SERVER_ERROR = "Internal server error";
export const USER_NOT_FOUND = "User does not exist";
export const USER_BLOCKED = "User is blocked";
export const USER_ALREADY_VERIFIED = "User already verified";
export const EMAIL_NOT_VERIFIED = "The user is not verified"
export const VERIFICATION_CODE_NOT_FOUND = "Verification code does not exist";
export const VERIFICATION_CODE_MISMATCH = "Verification code does not match";
export const VERIFICATION_CODE_EXPIRED = "Verification code is expired";
export const VERIFICATION_CODE_LIMIT_REACHED = "Daily verification code limit reached";
export const ACTIVE_SESSION_EXISTS = "A confirmation code has been sent to your email address to continue";
export const INVALID_AUTHORIZATION_HEADER = "Unauthorized - Invalid Authorization header";
export const INVALID_TOKEN_HEADER = "Unauthorized - Invalid token";
export const USER_NOTFOUND = "User not found";