export enum LegalizationService {
    RESIDENCE_CARD = "RESIDENCE_CARD",
    FAST_DECISION = "FAST_DECISION",
    RESERVATION_SUBMISSION = "RESERVATION_SUBMISSION",
    SWORN_TRANSLATION = "SWORN_TRANSLATION",
}